shared:
  image: node:18
  steps:
    - echo: echo hoge

jobs:
  job1:
    requires: [ ~commit ]
  job2:
    requires: []
  job3:
    requires: [ ~job2 ]
  job4:
    requires: [ ~job2 ]
  job5:
    requires: [ ~job1 ]
  job6:
    requires: []
  job7:
    requires: [ ~job6 ]
  job8:
    requires: [ ~job6 ]

stages:
  stage1:
    requires: [ ~job1 ]
    jobs: [ job2, job3, job4 ]
  stage2:
    requires: [ ~job5 ]
    jobs: [ job6, job7, job8 ]
